project:
  type: website
  output-dir: _site

website:
  title: "pysegy"
  navbar:
    left:
      - text: "Read"
        href: read.qmd
      - text: "Write"
        href: write.qmd
      - text: "Scan"
        href: scan.qmd
      - text: "API"
        href: reference/index.qmd

format:
  html:
    theme: cosmo

quartodoc:
  package: pysegy
  dir: reference
  source_dir: ..
  sections:
    - contents:
        - name: pysegy
          package: null
