name: Deploy Docs
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install python deps
        run: pip install quartodoc
      - name: Build API docs
        run: quartodoc build
        working-directory: docs
      - name: Render site
        run: quarto render docs
      - name: Deploy to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
